apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.appone.name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: janakisasidhar1/app-one
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  type : LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000


